### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by 191220029** [191220029/IR#1]
# Tasks
## IR Optimization

- [ ] **在生成机器码之前**，统计各基本块中用到的变量，记录在每个基本块的varTable_in中
- [ ] 到达定值分析：每个基本块中到达或无法到达定值的变量记录在varTable_out中

## MC Generation

- [ ] 根据每个基本快的varTable_in，给每个变量分配栈空间和寄存器（建议在StkRgManager中的构造函数实现）
注意：全局变量不一定会在基本块中使用。使用到的全局变量只需要分配寄存器。armv7-32bit 寄存器配置及其他事项详见MC.h和MC.cpp中注释。

- [ ] 利用StkRgManager记录的变量存储方式实现每个IR的CodeGen。每个基本块生成的机器码分为.data（全局变量定义）, .bss（全局变量声明）, .text三部分内容。
